name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"
          cache-dependency-path: setup.cfg
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('**/setup.cfg') }}-test
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -e .[all]
      - name: Lint mypy
        run: mypy src/ --ignore-missing-imports
      - name: Lint flake8
        run: flake8 src/ --max-line-length 120 --ignore=E203
      - name: Lint isort
        run: isort src --profile black -l 120
      - name: Interrogate docstring
        run: interrogate src 

            

            
      